{% set name = "mold" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rui314/mold/archive/v{{ version }}.tar.gz
  sha256: dcba90d5ee852ececb3a1a70110bb2d385079dcd1aa103e970296683c642f856

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  host:
    - mimalloc  # [not osx]
    - openssl  # [not osx]
    - tbb-devel
    - zlib
    - zstd

test:
  commands:
    - mold --version

about:
  home: https://github.com/rui314/mold
  license: MIT
  license_file: LICENSE
  summary: A Modern Linker

extra:
  recipe-maintainers:
    - apmorton
