{% set name = "mold" %}
{% set version = "2.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rui314/mold/archive/v{{ version }}.tar.gz
  sha256: 32a0917894b9bc9317ba5d6bdbcad8401513bcdfbbbcfc9de55423c46db8511c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

  host:
    - mimalloc  # [not osx]
    - openssl  # [not osx]
    - tbb-devel
    - zlib
    - zstd

test:
  commands:
    - mold --version

about:
  home: https://github.com/rui314/mold
  license: MIT
  license_file: LICENSE
  summary: A Modern Linker

extra:
  recipe-maintainers:
    - apmorton
