{% set name = "mold" %}
{% set version = "2.32.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rui314/mold/archive/v{{ version }}.tar.gz
  sha256: f3c9a527d884c635834fe7d79b3de959b00783bf9446280ea274d996f0335825

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

  host:
    - mimalloc  # [not osx]
    - openssl  # [not osx]
    - tbb-devel
    - zlib
    - zstd

test:
  commands:
    - mold --version

about:
  home: https://github.com/rui314/mold
  license: MIT
  license_file: LICENSE
  summary: A Modern Linker

extra:
  recipe-maintainers:
    - apmorton
