{% set name = "mold" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rui314/mold/archive/v{{ version }}.tar.gz
  sha256: 6cfc1af0214f993be1b0ae4a2f0278d32b7fc48155c15b2d03758f6d81e7250b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  host:
    - mimalloc  # [not osx]
    - openssl  # [not osx]
    - tbb-devel
    - zlib
    - zstd

test:
  commands:
    - mold --version

about:
  home: https://github.com/rui314/mold
  license: MIT
  license_file: LICENSE
  summary: A Modern Linker

extra:
  recipe-maintainers:
    - apmorton
